// Copies the JSON the app needs from ../data into public/data/<name>.<sha256:8>.json and
// writes src/generated/data-manifest.ts so the bundle knows the content-hashed URLs
// without an extra round trip (docs/ARCHITECTURE.md, docs/DEPLOY.md "Build contract").
//
// songs: uses ../data/songs.slim.json (no rawFields, minified) when it is present and not
// older than songs.json; otherwise strips rawFields from songs.json itself.
// Fails loudly when ../data/songs.json is missing so a broken checkout cannot deploy.
import { createHash } from 'node:crypto'
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const appDir = resolve(here, '..')
const dataDir = resolve(appDir, '..', 'data')
const outDir = join(appDir, 'public', 'data')
const genDir = join(appDir, 'src', 'generated')

const songsPath = join(dataDir, 'songs.json')
if (!existsSync(songsPath)) {
  console.error(`sync-data: ${songsPath} not found. The dataset must be committed under data/.`)
  process.exit(1)
}

/** name -> { text, source } */
const files = {}

// songs: slim copy preferred
const slimPath = join(dataDir, 'songs.slim.json')
if (existsSync(slimPath) && statSync(slimPath).mtimeMs >= statSync(songsPath).mtimeMs) {
  files.songs = { text: readFileSync(slimPath, 'utf8'), source: 'songs.slim.json' }
} else {
  const full = JSON.parse(readFileSync(songsPath, 'utf8'))
  const strip = (v) => {
    if (Array.isArray(v)) return v.filter((x) => x !== null && x !== undefined).map(strip)
    if (v && typeof v === 'object') {
      const o = {}
      for (const [k, x] of Object.entries(v)) if (k !== 'rawFields') o[k] = strip(x)
      return o
    }
    return v
  }
  files.songs = { text: JSON.stringify(full.map(strip)), source: 'songs.json (rawFields stripped)' }
}

// the other files: required ones fail, optional ones are skipped when absent
const required = ['places', 'facets']
const optional = ['journeys', 'journeys-curated', 'villages', 'context-events']
for (const name of [...required, ...optional]) {
  const p = join(dataDir, `${name}.json`)
  if (!existsSync(p)) {
    if (required.includes(name)) {
      console.error(`sync-data: ${p} not found.`)
      process.exit(1)
    }
    continue
  }
  files[name] = { text: JSON.stringify(JSON.parse(readFileSync(p, 'utf8'))), source: `${name}.json` }
}
// legibility (wax-cylinder filter), optional: the app copy of data/recording-quality.json keeps
// what the explorer and the song page read: record score, the track it came from and the clip-only
// flag; every track's own score; the clip list. Written by audio/run_legibility.py and
// audio/quality_records.py.
const qualityPath = join(dataDir, 'recording-quality.json')
if (existsSync(qualityPath)) {
  const q = JSON.parse(readFileSync(qualityPath, 'utf8'))
  const records = {}
  for (const id of Object.keys(q.records ?? {}).sort()) {
    const r = q.records[id]
    records[id] = r.flag === 'clip-only' ? [r.legib, r.track, 1] : [r.legib, r.track]
  }
  files.legibility = {
    text: JSON.stringify({ method: q.method, scoredAt: q.scoredAt, records, tracks: q.tracks ?? {}, clips: q.clips ?? [] }),
    source: 'recording-quality.json',
  }
}
// geo layers (journey mapper), optional
const geoDir = join(dataDir, 'geo')
if (existsSync(geoDir)) {
  for (const f of readdirSync(geoDir).filter((f) => f.endsWith('.json')).sort()) {
    const name = `geo/${f.replace(/\.json$/, '')}`
    files[name] = { text: JSON.stringify(JSON.parse(readFileSync(join(geoDir, f), 'utf8'))), source: `geo/${f}` }
  }
}

rmSync(outDir, { recursive: true, force: true })
mkdirSync(outDir, { recursive: true })
mkdirSync(join(outDir, 'geo'), { recursive: true })
mkdirSync(genDir, { recursive: true })

const manifest = {}
const report = []
for (const [name, { text, source }] of Object.entries(files)) {
  const hash = createHash('sha256').update(text).digest('hex').slice(0, 8)
  const rel = `${name}.${hash}.json`
  writeFileSync(join(outDir, rel), text)
  manifest[name] = `/data/${rel}`
  report.push(`  ${rel.padEnd(34)} ${(Buffer.byteLength(text) / 1048576).toFixed(2).padStart(7)} MB  (from ${source})`)
}

const keys = Object.keys(manifest).sort()
const ts = [
  '// Generated by scripts/sync-data.mjs. Do not edit; do not commit.',
  'export const dataManifest = {',
  ...keys.map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(manifest[k])},`),
  '} as const',
  'export type DataFileName = keyof typeof dataManifest',
  '',
].join('\n')
writeFileSync(join(genDir, 'data-manifest.ts'), ts)

// tokens: single source of truth is ../app-tokens/tokens.css
const tokensSrc = resolve(appDir, '..', 'app-tokens', 'tokens.css')
if (!existsSync(tokensSrc)) {
  console.error(`sync-data: ${tokensSrc} not found.`)
  process.exit(1)
}
writeFileSync(join(genDir, 'tokens.css'), readFileSync(tokensSrc, 'utf8'))

console.log(`sync-data: wrote ${keys.length} files to public/data and src/generated/data-manifest.ts`)
console.log(report.join('\n'))
